---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nvidia.github.io/k8s-device-plugin
      chart: nvidia-device-plugin
      version: 0.12.2
      sourceRef:
        kind: HelmRepository
        name: nvidia-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.9.0
    nodeSelector:
      feature.node.kubernetes.io/pci-0300_10de.present: "true"
    tolerations:
    - key: nvidia.com/gpu
      operator: Exists
