---
# Enable to skip apt upgrade
skip_upgrade_packages: false
# Enable to skip removing crufty packages
skip_remove_packages: false

# Timezone for the servers
timezone: "America/Chicago"

# Set custom ntp servers
ntp_servers:
  primary:
    - "gw.dfw.56k.sh"
  fallback:
    - "0.us.pool.ntp.org"
    - "1.us.pool.ntp.org"
    - "2.us.pool.ntp.org"
    - "3.us.pool.ntp.org"
# Additional ssh public keys to add to the nodes
# ssh_authorized_keys:
