apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: security
stringData:
    username: ENC[AES256_GCM,data:uuaUQ1J89b4=,iv:AkbpeJ2EOCDi1RKe0EcMlj3x/82TXJv06v3PHCuSOnw=,tag:wXCxiWxmkNuZD97Gf7GJCw==,type:str]
    password: ENC[AES256_GCM,data:Cjb7ANHWK63wYJ9jKXrYxQ==,iv:Mr9aXkmzHhxXkQWwG5629YcQiKVkaiW2AuNrRWRWFNg=,tag:ldiCrv+1S3FOyTnpmPZs4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeVlSUVhhcHg5NFV3aG5H
            WDVSdm5FVlZBSWE5b3ZCaFpBL1AzM2RlOXpjCnNKRHRjdHo1Z2ZmeEt3NzNHYmJJ
            ZXNOQTRHc2wxWDM1TFJucGFHeXkzZm8KLS0tIFdGZ0xhWkwwSnJBK2xRMUZic0k0
            WUZ0QUVZZWJndzVMQTB0RUJhakpWYTQKf5Ll0neEoV1dwKIg5oL2Js5c4Okk1wtl
            0rNcSsEggiQpu40j5yR/yKnfhqzFBLKAlpEXEp2MNAUIm2Rv5QEt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-24T22:19:21Z"
    mac: ENC[AES256_GCM,data:rQLB7vWtLxA9anYtO3fcWxwOdFDYgkNLlCHXRUZCXXFwhk09Xr2sGOQsZeFBGUQpOxAtVmR4V9tAXrjapr6N8deFWk2SRwlQPdQNL3/wHZQfImOASabkPuZHA+vS6HocEcoT4dCF8GueEaIx8Vx7TUOPyAQ3reoQIIVlHd/qLIk=,iv:fwdMKJ5oI4N/GDNxL92zPz7l61qszpAd2ssproCkMcw=,tag:lc/bzhru6XW7dCAmv27bEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-app
    namespace: security
stringData:
    username: ENC[AES256_GCM,data:QvzX,iv:2GnnS0JTIqv4x4KW/mTUfWKlMr2uJ+ceJZ572NMjc4M=,tag:Q2kWvVXyJykiUfVgXxNJJA==,type:str]
    password: ENC[AES256_GCM,data:e1eBTMvtE/Uxv8/pNFGOAQ==,iv:vrVBV2BqbkyV+h8dGNurnAQPx6FpVC9ZLQSAarV8B9c=,tag:MvXr6FI3tVWOK/SoRP9qeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeVlSUVhhcHg5NFV3aG5H
            WDVSdm5FVlZBSWE5b3ZCaFpBL1AzM2RlOXpjCnNKRHRjdHo1Z2ZmeEt3NzNHYmJJ
            ZXNOQTRHc2wxWDM1TFJucGFHeXkzZm8KLS0tIFdGZ0xhWkwwSnJBK2xRMUZic0k0
            WUZ0QUVZZWJndzVMQTB0RUJhakpWYTQKf5Ll0neEoV1dwKIg5oL2Js5c4Okk1wtl
            0rNcSsEggiQpu40j5yR/yKnfhqzFBLKAlpEXEp2MNAUIm2Rv5QEt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-24T22:19:21Z"
    mac: ENC[AES256_GCM,data:rQLB7vWtLxA9anYtO3fcWxwOdFDYgkNLlCHXRUZCXXFwhk09Xr2sGOQsZeFBGUQpOxAtVmR4V9tAXrjapr6N8deFWk2SRwlQPdQNL3/wHZQfImOASabkPuZHA+vS6HocEcoT4dCF8GueEaIx8Vx7TUOPyAQ3reoQIIVlHd/qLIk=,iv:fwdMKJ5oI4N/GDNxL92zPz7l61qszpAd2ssproCkMcw=,tag:lc/bzhru6XW7dCAmv27bEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: security
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:3heHftSg/vVtFA==,iv:Mv5ZZWRGCR3yuRd1Ek55KcPsifXhNExTPF8fwgSnDm4=,tag:wo8dhSd5zgxWcW/W+7ac0g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:HpCurRA1bZUjxD1GhCvHgvx1CUBBaVHM,iv:hvGDF9exprjgOcsu0MLcB6oW19hFcppNTKl+jsDfeIY=,tag:msc3p5tnKpZiqF9sUjhjSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeVlSUVhhcHg5NFV3aG5H
            WDVSdm5FVlZBSWE5b3ZCaFpBL1AzM2RlOXpjCnNKRHRjdHo1Z2ZmeEt3NzNHYmJJ
            ZXNOQTRHc2wxWDM1TFJucGFHeXkzZm8KLS0tIFdGZ0xhWkwwSnJBK2xRMUZic0k0
            WUZ0QUVZZWJndzVMQTB0RUJhakpWYTQKf5Ll0neEoV1dwKIg5oL2Js5c4Okk1wtl
            0rNcSsEggiQpu40j5yR/yKnfhqzFBLKAlpEXEp2MNAUIm2Rv5QEt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-24T22:19:21Z"
    mac: ENC[AES256_GCM,data:rQLB7vWtLxA9anYtO3fcWxwOdFDYgkNLlCHXRUZCXXFwhk09Xr2sGOQsZeFBGUQpOxAtVmR4V9tAXrjapr6N8deFWk2SRwlQPdQNL3/wHZQfImOASabkPuZHA+vS6HocEcoT4dCF8GueEaIx8Vx7TUOPyAQ3reoQIIVlHd/qLIk=,iv:fwdMKJ5oI4N/GDNxL92zPz7l61qszpAd2ssproCkMcw=,tag:lc/bzhru6XW7dCAmv27bEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
