---
version: "3"

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  backup: .taskfiles/BackupTasks.yml
  cluster: .taskfiles/ClusterTasks.yml
  debug: .taskfiles/DebugTasks.yml
  precommit: .taskfiles/PreCommitTasks.yml
  restore: .taskfiles/RestoreTasks.yml
  terraform: .taskfiles/TerraformTasks.yml
