---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database

resources:
  - https://raw.githubusercontent.com/movetokube/postgres-operator/1.1.1/deploy/operator.yaml
  - https://raw.githubusercontent.com/movetokube/postgres-operator/1.1.1/deploy/role.yaml
  - https://raw.githubusercontent.com/movetokube/postgres-operator/1.1.1/deploy/role_binding.yaml
  - https://raw.githubusercontent.com/movetokube/postgres-operator/1.1.1/deploy/service_account.yaml
images:
  - name: movetokube/postgres-operator
    newTag: 1.1.1
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ext-postgres-operator
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/envFrom
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: ext-postgres-operator
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
          - monitoring.coreos.com
          resources:
          - 'servicemonitors'
          verbs:
          - '*'
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ext-postgres-operator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POSTGRES_URI_ARGS
          value: ""
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POSTGRES_HOST
          value: postgres-default-rw.database.svc.cluster.local
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-default-superuser
              key: username
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-default-superuser
              key: password
