# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr
    namespace: media
type: Opaque
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:PEJl29qwDCCqLhqgwt2xSn/Mjv64IUukIxZj91BVUxA=,iv:D3JP76r+D2lzTMg1omyI8PW8ExEPa1ZyI/TLZFCo+20=,tag:jCkfMbvTcLSxEamSKs0S0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUjFSMEZ2UGJieThuc2I0
            ZmhxVVlYVWNpc2k4WkFnVVhmT3IyeTZPaGdZCnRuOUcweWQ1Tlo4eTFDcWNRS0ZG
            MUU3WXpSYW5HTzI2N0o1RXFuTnp6L0EKLS0tIGt3NnYyT1prbGFMa1dkb3VUcWs2
            UjNodkRnWDh5TTNLVUZrNHc4OGo0aWsKvT3D5YTOCOdNKY3giqchtfibp/K//1zX
            3uDoqm3aB3w2fInJrTRpr8hm+IYvWLsi3a/FYJlp4uiMwFeg+Rvczg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T03:21:54Z"
    mac: ENC[AES256_GCM,data:Euf93NiSGfimNIhA8g0pZvPCE8J0Nwhhm/D20piu6DmtXN5PDnN93NkRobw1LoNr67REnMaUndisdvYlY9H+BC37X3iWaU43FSJ1oAe9L2WH7ub2GPDBns9LaJrRIUZ4Y16bqpe973LXEd/CuYdL1OBCiwEYVFS36k6BDodxQWQ=,iv:n0L20TjyBkyJWL+xvG8J2Z+TU13cXP7FlvGZKiYpIm0=,tag:6OcW6+vpcBRGm/MYoOjALw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
