---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: vaultwarden-db
  namespace: security
spec:
  database: vaultwarden
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: vaultwarden-user
  namespace: security
spec:
  role: vaultwarden
  database: vaultwarden-db
  secretName: database
  privileges: OWNER
