---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: security
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      labels:
        pmb.home.arpa/backup-claim: &claimName "vaultwarden-config-v1"
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: 1.25.1@sha256:ea7901a9629897801b38b6afbce1869d357ebb9e080ec6ffff5839d85d8a79e4
    env:
      DATA_FOLDER: "config"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://warden.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      SMTP_HOST: "smtp.sendgrid.net"
      SMTP_FROM: "no-reply@56k.jp"
      SMTP_FROM_NAME: "Vaultwarden"
      SMTP_SSL: true
      SMTP_PORT: 587
      SMTP_USERNAME: "apikey"
      SMTP_PASSWORD: "${SECRET_SENDGRID_API_KEY}"
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-postgres
            key: POSTGRES_URL
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: "form-textbox-password"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: "warden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: *websocket-port
        tls:
          - hosts:
              - "warden.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: *claimName
