---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.4@sha256:db4a6069aa909a6e440674f5e74881096aa3c0d78bb2178419587d28fcd20012
        env:
          - name: POSTGRES_HOST
            value: postgres-downloads-rw
          - name: POSTGRES_DB
            value: radarr radarr-log
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-app
                key: username
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-app
                key: password
