# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: media
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:HiCQIAmOy9dtIQm9RqQXk4xHngn43WBDjmSs+hQgVuE=,iv:QbMphWbF07XRtg3zJ9Y0NL7Y2pScsDq1I3IGZeqJAQ4=,tag:4XI0EUsw+vzDnzaSN/BGTA==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:HFtQe7H43UtJW/Hfwjz9GAvXw+69a/XTDwvw4aUI040=,iv:1VHYQd0TMZr3gtoe6MmGI+OFl1JkYon2UaONLucDkac=,tag:Vnvaww7ZS5M8xESG79QXHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTkQ0WUJzNUtyZ0JDUGJh
            SC81cm9BcWszK2xHbDdpT1BobzRPZ1RsTlFFCldLblI3WlM2cFRKU3UveWxLSFFV
            Rkh5elpreWt2a0VwVlp2bVFmRnhxYU0KLS0tIGdOaTNEQVJpYnFJR3o2ZVhGV0Yx
            VmUzSmMxN0hXbmNmTVdsVXB1RFEyNWsKgZwXuYGDkW1ZmJ61VtCskjnM3AdM6Gpl
            bEvsh9093tys58Srb2K1qfj1BH7mHxVqbCwLz+9JopnYlYGsL7A+IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T04:05:06Z"
    mac: ENC[AES256_GCM,data:73pMuoj+y+rgHUCesFRNVjyudqkZrY0H2eBIeb3jz4VFKIBMlA5/KjfHpO7QcsUO+V6feD02yID0myKqYDPU0pOfzD7vAIhWQvbbcLOD3ozhjvzVcLnGHNohcZLdEv0b3CbmPlwrlk/rYot2GKYi3JxdG8DgEdweh417Dmi2qjs=,iv:FGC6jKt1JWdViim/1W+a2mZu6/sWhD5E5YRXQjQ9XIE=,tag:qIQ8YQcDytTS5asqXLJ0mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
