---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.deliveryhero.io/
      chart: node-problem-detector
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/node-problem-detector/node-problem-detector
      tag: v0.8.10
    metrics:
      serviceMonitor:
        enabled: true
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: DaemonSet
              name: node-problem-detector
            patch:
              - op: replace
                path: /spec/template/spec/containers/0/volumeMounts
                value:
                  - name: log
                    readOnly: true
                    mountPath: /var/log/
                  - name: custom-config
                    readOnly: true
                    mountPath: /custom-config
