---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://codecentric.github.io/helm-charts
      chart: keycloak
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: codecentric-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jboss/keycloak
      tag: 13.0.1
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_USER
        value: "${SECRET_KEYCLOAK_ADMIN_USER}"
      - name: KEYCLOAK_PASSWORD
        value: "${SECRET_KEYCLOAK_ADMIN_PASSWORD}"
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      rules:
      - host: "idp.${SECRET_DOMAIN}"
        paths:
        - /
      tls:
      - hosts:
        - "idp.${SECRET_DOMAIN}"
    postgresql:
      enabled: true
      postgresqlPassword: "${SECRET_KEYCLOAK_POSTGRES_PASSWORD}"
      persistence:
        size: 10Gi
