---

# IP address of node
ansible_host: "10.75.40.10"

# Ansible user to ssh into servers with
ansible_user: "ubuntu"
# ansible_ssh_pass: "ubuntu"
# ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null"
ansible_become_pass: "ubuntu"

# Set enabled to true to mark this host as running a distributed storage rook-ceph
rook_ceph:
  enabled: false
  # devices:
  # - /dev/nvme0n1
