---
access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

  rules:
    # - domain: "auth.${SECRET_PUBLIC_DOMAIN}"
    #   policy: bypass

    # - domain: "*.${SECRET_PUBLIC_DOMAIN}"
    #   policy: bypass
    #   networks: ["internal"]

    # - domain:
    #     - "radarr-test.${SECRET_PUBLIC_DOMAIN}"
    #   policy: bypass
    #   resources: ["^/api([?/].*)?$"]

    # - domain: ["*.${SECRET_PUBLIC_DOMAIN}"]
    #   policy: bypass
    #   networks: ["internal"]
