---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-downloads
  namespace: downloads
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-app
  monitoring:
    enablePodMonitor: true
