---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-downloads
  namespace: downloads
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-app
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://minio.default:9000
      serverName: "postgres-downloads-v1"
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
