apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: downloads
stringData:
    username: ENC[AES256_GCM,data:uuaUQ1J89b4=,iv:AkbpeJ2EOCDi1RKe0EcMlj3x/82TXJv06v3PHCuSOnw=,tag:wXCxiWxmkNuZD97Gf7GJCw==,type:str]
    password: ENC[AES256_GCM,data:Cjb7ANHWK63wYJ9jKXrYxQ==,iv:Mr9aXkmzHhxXkQWwG5629YcQiKVkaiW2AuNrRWRWFNg=,tag:ldiCrv+1S3FOyTnpmPZs4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeVlSUVhhcHg5NFV3aG5H
            WDVSdm5FVlZBSWE5b3ZCaFpBL1AzM2RlOXpjCnNKRHRjdHo1Z2ZmeEt3NzNHYmJJ
            ZXNOQTRHc2wxWDM1TFJucGFHeXkzZm8KLS0tIFdGZ0xhWkwwSnJBK2xRMUZic0k0
            WUZ0QUVZZWJndzVMQTB0RUJhakpWYTQKf5Ll0neEoV1dwKIg5oL2Js5c4Okk1wtl
            0rNcSsEggiQpu40j5yR/yKnfhqzFBLKAlpEXEp2MNAUIm2Rv5QEt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-23T00:22:50Z"
    mac: ENC[AES256_GCM,data:5xdaYaks825JoT5TY02GS2tFrip8NITYZQ16/lwYEbFme+aTpJthzOMyVZ4fxZkPUOdg6kWoAr1yxMcCipMLcqtxRFQbHeYMb98bvsgzcIpPpAt9reE9B1rMB7f6NdxIASHvUHW97+bjZE2ZhXCwoTHjCVM4vTercfZrwLu6M/I=,iv:LvRFER8t4wEBx9EoDKj+LQq/h9kSIROio+c88bFHwKE=,tag:biAZNthRcMV20mQn4FXSOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-app
    namespace: downloads
stringData:
    username: ENC[AES256_GCM,data:QvzX,iv:2GnnS0JTIqv4x4KW/mTUfWKlMr2uJ+ceJZ572NMjc4M=,tag:Q2kWvVXyJykiUfVgXxNJJA==,type:str]
    password: ENC[AES256_GCM,data:qtTiBujQjeLubOHXwWs5dw==,iv:UedkIi+A3DaT7OSHKc0rT202uBkMauYN1Ng/KZCDpRA=,tag:KIh7xstFIQpf+LQwSfDpnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeVlSUVhhcHg5NFV3aG5H
            WDVSdm5FVlZBSWE5b3ZCaFpBL1AzM2RlOXpjCnNKRHRjdHo1Z2ZmeEt3NzNHYmJJ
            ZXNOQTRHc2wxWDM1TFJucGFHeXkzZm8KLS0tIFdGZ0xhWkwwSnJBK2xRMUZic0k0
            WUZ0QUVZZWJndzVMQTB0RUJhakpWYTQKf5Ll0neEoV1dwKIg5oL2Js5c4Okk1wtl
            0rNcSsEggiQpu40j5yR/yKnfhqzFBLKAlpEXEp2MNAUIm2Rv5QEt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-23T00:22:50Z"
    mac: ENC[AES256_GCM,data:5xdaYaks825JoT5TY02GS2tFrip8NITYZQ16/lwYEbFme+aTpJthzOMyVZ4fxZkPUOdg6kWoAr1yxMcCipMLcqtxRFQbHeYMb98bvsgzcIpPpAt9reE9B1rMB7f6NdxIASHvUHW97+bjZE2ZhXCwoTHjCVM4vTercfZrwLu6M/I=,iv:LvRFER8t4wEBx9EoDKj+LQq/h9kSIROio+c88bFHwKE=,tag:biAZNthRcMV20mQn4FXSOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
