---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr-uhd
  namespace: downloads
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.4@sha256:198e463d6211d32ce8c8ce22dff47ab4bad84ce9425a4b524f9bf4d6949d89b8
        env:
          - name: POSTGRES_HOST
            value: postgres-downloads-rw
          - name: POSTGRES_DB
            value: radarr-uhd radarr-uhd-log
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-app
                key: username
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-app
                key: password
