---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5