apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:uuaUQ1J89b4=,iv:AkbpeJ2EOCDi1RKe0EcMlj3x/82TXJv06v3PHCuSOnw=,tag:wXCxiWxmkNuZD97Gf7GJCw==,type:str]
    password: ENC[AES256_GCM,data:Cjb7ANHWK63wYJ9jKXrYxQ==,iv:Mr9aXkmzHhxXkQWwG5629YcQiKVkaiW2AuNrRWRWFNg=,tag:ldiCrv+1S3FOyTnpmPZs4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeVlSUVhhcHg5NFV3aG5H
            WDVSdm5FVlZBSWE5b3ZCaFpBL1AzM2RlOXpjCnNKRHRjdHo1Z2ZmeEt3NzNHYmJJ
            ZXNOQTRHc2wxWDM1TFJucGFHeXkzZm8KLS0tIFdGZ0xhWkwwSnJBK2xRMUZic0k0
            WUZ0QUVZZWJndzVMQTB0RUJhakpWYTQKf5Ll0neEoV1dwKIg5oL2Js5c4Okk1wtl
            0rNcSsEggiQpu40j5yR/yKnfhqzFBLKAlpEXEp2MNAUIm2Rv5QEt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-29T01:43:15Z"
    mac: ENC[AES256_GCM,data:4DA0D24+w3+OK74iQwMqs4NZh1NLJK70E8TaVzv8hSJg9fiiuCNq/xUvm6LCoZGMklRbsP1YlL3YH6O8esA4uVkgbClvlKZtBYgEQU7hfSAEYZ9VqT1fNNO7D+/YZSYQs0sTb95ltMrRvXXcYxHpnWtDrFefw5PBaL9PHpWxJPA=,iv:yyKZWjZ2sz9jcYj40efPqsBpqYMLdX1qfMX3hK0LK5Q=,tag:irycBejZtTl1GGPQrfTRNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
