---
- include: addons.yml
  tags:
    - addons

- name: k3s | cluster configuration
  include_role:
    name: xanmanning.k3s
    public: true

- include: cleanup.yml
  tags:
    - cleanup

- include: kubeconfig.yml
  tags:
    - kubeconfig
