---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - lidarr
  - overseerr
  - postgres
  - prowlarr
  - qbittorrent
  - radarr
  - radarr-uhd
  - recyclarr
  - sabnzbd
  - scripts
  - sonarr
  - sonarr-uhd
