---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: benji
  namespace: backup-system
spec:
  releaseName: benji
  interval: 5m
  chart:
    spec:
      chart: ./charts/benji-k8s
      version: 0.2.0
      sourceRef:
        kind: GitRepository
        name: benji-charts
        namespace: flux-system
      interval: 5m
  values:
    timeZone: America/Chicago
    benji:
      image:
        registry: ghcr.io
        repository: elemental-lf/benji-k8s
        tag: 0.15.0
        pullPolicy: IfNotPresent
      configuration:
        configurationVersion: '1'
        databaseEngine: postgresql://benji:secret@benji-postgresql-headless:5432/benji
        defaultStorage: storage-1
        storages:
          - name: storage-1
            storageId: 1
            module: file
            configuration:
              path: /backup-franxx
        ios:
          - module: rbdaio
            name: k8s-fast-pool
            configuration:
              simultaneousReads: 3
              simultaneousWrites: 3
              cephConfigFile: /etc/ceph/ceph.conf
              clientIdentifier: admin
              newImageFeatures:
                - RBD_FEATURE_LAYERING
                - RBD_FEATURE_EXCLUSIVE_LOCK
                - RBD_FEATURE_STRIPINGV2
                - RBD_FEATURE_OBJECT_MAP
                - RBD_FEATURE_FAST_DIFF
                - RBD_FEATURE_DEEP_FLATTEN
      cronJob:
        activeDeadlineSeconds: null
        startingDeadlineSeconds: null
      crontab:
        - name: backup-security
          schedule: "00 03 * * *"
          command:
            - benji-backup-pvc
            - --namespace
            - security
        - name: backup-media
          schedule: "00 03 * * *"
          command:
            - benji-backup-pvc
            - --namespace
            - media
        - name: backup-mail
          schedule: "00 03 * * *"
          command:
            - benji-backup-pvc
            - --namespace
            - mail
        - name: enforce
          schedule: "00 04 * * *"
          command:
            - benji-command
            - enforce
            - days14
            - 'labels["benji-backup.me/instance"] == "benji-k8s"'
        - name: cleanup
          schedule: "00 05 * * *"
          command:
            - benji-command
            - cleanup
      volumes:
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
            defaultMode: 0444
        - name: backup-franxx
          persistentVolumeClaim:
            claimName: nfs-backup-franxx-pvc
      volumeMounts:
        - name: ceph-etc
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
          readOnly: true
        - name: ceph-keyring
          mountPath: /etc/ceph/keyring
          subPath: keyring
          readOnly: true
        - name: backup-franxx
          mountPath: /backup-franxx
    fsfreeze:
      enabled: true
    postgresql:
      enabled: true
      postgresqlUsername: benji
      postgresqlDatabase: benji
      postgresqlPassword: secret
    pushgateway:
      image:
        registry: docker.io
        repository: prom/pushgateway
        tag: v0.10.0
        pullPolicy: IfNotPresent
      nameOverride: pushgateway
