apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: downloads
type: Opaque
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:tW2WMKM147Wc8Fqv41k4JGAb4lY1Cbe7Bzh2i+2B,iv:GhAxauIXAr4eB9ZdbVy9HyP0FincuNVmY2OUD/jRxg8=,tag:BYEfNMWmK0UJYXkzyUEpMA==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:reFkPTLFK+o1LRyuat0J+OYvpB+xUJdzhjaLdLaE,iv:IWoWix3HMtqhWmVyyhn9KaHx707DX6nc4C6A6RniE40=,tag:VQO07bVJa4/huIzLH93opg==,type:str]
    RADARR__API_KEY: ENC[AES256_GCM,data:9onz9w2ZYN23AIjtEODhWkmENZ19gcpIoHc96EKkY5I=,iv:XZF+zz3vlMFfmQUKpQdWOuu82X1Tp+QV5EctyZghkHE=,tag:7yAgeBzxrvRoXhWn5r2VtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VlE3eGJRanM4bkdLaTkx
            djA5TTkrYjJGQURyc2dTZzJxSXZWNml0Vkh3CjRzakdpUit1YnpTb2FDRzhhc3NN
            dlVqeG11TEZvL2k4dFVqYVB5UWRRRm8KLS0tIFNqUUdWVk0zVVFwZUVhd2Z6SnlO
            VllWbWdqYmlGbm1GUlYzL0d1UGE2TWcKs759AHIQ7EP9UQSUJisdeg3CAEGCteFJ
            ziEjj0kMumja6I0zRakr/6xXn4CQQOdhq39t+dmIK8OXgN7owrEDgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T03:24:25Z"
    mac: ENC[AES256_GCM,data:IZRTxQSw/ojLOl5WseojFmPSIj5bYYltU4vxr83ivQUp3gfQt3mjYNAwbBdHes6G0SIQ5r06Fzr1AF0VihHOLNK5AZFKjlV+TW8pecVYctizkfCmRFWlfUtgyhsvhyNHjS/rAkohhU8/NXCU0Olr2RJxB1G0buAM93JcSD9ct+Y=,iv:QIVOANeq2/1llJMcLiqN9o67U2YdGHs8DjiyDTZHvcU=,tag:Gk3nfBMGfCbYmc7IdJe6Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
