---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.16.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    extraEnvVars:
    - name: slackHookUrl
      valueFrom:
        secretKeyRef:
          name: kured-discord-secret
          key: webhook
    configuration:
      startTime: "3:00"
      endTime: "6:00"
      timeZone: "America/Chicago"
    tolerations:
    - operator: "Exists"
      effect: "NoSchedule"
    metrics:
      create: true
