---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre-web
      tag: version-0.6.13
    env:
      TZ: "America/Chicago"
      PUID: 5600
      PGID: 5600
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v1
      media:
        enabled: true
        existingClaim: nfs-media-franxx-pvc
        mountPath: /data/media-franxx
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/calibreweb/dracula.css"></head>';
            sub_filter_once on;
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
        hosts:
        - host: "books.${SECRET_PUBLIC_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - "books.${SECRET_PUBLIC_DOMAIN}"
    resources:
      requests:
        memory: 256Mi
    probes:
      startup:
        spec:
          periodSeconds: 15
