---

- name: k3s-agent | enable nvidia-container-runtime
  ansible.builtin.copy:
    src: files/config.toml.tmpl
    dest: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
  register: containerd_config

- name: k3s-agent | restart agent
  service:
    name: k3s
    state: restarted
  when: containerd_config.changed
