---

- name: patch | create patch directory
  ansible.builtin.file:
    path: /opt/nvidia-patch
    state: directory
    mode: '0755'

- name: patch | download nvidia-patch
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/keylase/nvidia-patch/{{ nvidia_patch.version }}/patch.sh
    dest: /opt/nvidia-patch/patch.sh
    checksum: "{{ nvidia_patch.checksum }}"
    mode: '0755'

- name: patch | patch current nvidia driver
  ansible.builtin.command:
    cmd: /opt/nvidia-patch/patch.sh
