---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: szurubooru-db
  namespace: media
spec:
  database: szurubooru
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: szurubooru-user
  namespace: media
spec:
  role: szurubooru
  database: szurubooru-db
  secretName: database
  privileges: OWNER
