---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app szurubooru
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/toboshii/szurubooru
      tag: 2.5-edge
      pullPolicy: Always
    initContainers:
      wait-for-db:
        image: ghcr.io/patrickdappollonio/wait-for:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: database-szurubooru-user
                key: HOST
        command:
          - /wait-for
        args:
          - --host="$(POSTGRES_HOST):5432"
          - --verbose
    env:
      TZ: "${TIMEZONE}"
      BACKEND_HOST: localhost
      BASE_URL: /
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-image"
          hajimari.io/appName: "Booru"
        hosts:
          - host: &host "${SECRET_PUBLIC_DOMAIN_3}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    additionalContainers:
      server:
        name: server
        image: ghcr.io/toboshii/szurubooru-server:2.5-edge
        imagePullPolicy: Always
        env:
          - name: TZ
            value: "${TIMEZONE}"
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: database-szurubooru-user
                key: POSTGRES_URL
        ports:
          - name: server-http
            containerPort: 6666
            protocol: TCP
        volumeMounts:
          - name: media
            mountPath: /data
          - name: config
            mountPath: /opt/app/config.yaml
            subPath: config.yaml
    podSecurityContext:
      supplementalGroups:
        - 5600
    persistence:
      config:
        enabled: true
        type: "custom"
        mountPath: "/opt/app/config.yaml"
        subPath: "config.yaml"
        volumeSpec:
          configMap:
            name: "szurubooru-settings"
      media:
        enabled: true
        type: nfs
        server: "nas01.${SECRET_PRIVATE_DOMAIN}"
        path: /tank/share/Images/Booru
        mountPath: /data
