---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app szurubooru
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/szurubooru
      tag: 2.5-edge
      pullPolicy: Always
    env:
      TZ: "${TIMEZONE}"
      BACKEND_HOST: localhost
      BASE_URL: /
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN_3}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-image"
          hajimari.io/appName: "Booru"
        hosts:
        - host: &host "${SECRET_PUBLIC_DOMAIN_3}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
    additionalContainers:
      server:
        name: server
        image: ghcr.io/toboshii/szurubooru-server:2.5-edge
        imagePullPolicy: Always
        env:
          TZ: "${TIMEZONE}"
        ports:
        - name: server-http
          containerPort: 6666
          protocol: TCP
        volumeMounts:
        - name: media
          mountPath: /data
        - name: config
          mountPath: /opt/app/config.yaml
          subPath: config.yaml
    persistence:
      config:
        enabled: true
        type: "custom"
        mountPath: "/opt/app/config.yaml"
        subPath: "config.yaml"
        volumeSpec:
          configMap:
            name: "{{ .Release.Name }}-settings"
      media:
        enabled: true
        type: nfs
        server: "nas01.${SECRET_PRIVATE_DOMAIN}"
        path: /tank/share/Images/Booru
        mountPath: /data
    podSecurityContext:
      supplementalGroups:
      - 5600
    postgresql:
      enabled: true
      postgresqlUsername: szurubooru
      postgresqlPassword: "${SECRET_BOORU_POSTGRES_PASSWORD}"
      postgresqlDatabase: szurubooru
      persistence:
        enabled: true
        storageClass: ceph-block
        accessModes:
        - ReadWriteOnce
        size: 5Gi
