---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - database.yaml
  - helm-release.yaml
configMapGenerator:
  - name: szurubooru-settings
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true