---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
configMapGenerator:
  - name: szurubooru-settings
    files:
      - config.yaml