---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-fic-config-v1
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre-web-fic
    app.kubernetes.io/instance: *name
    pmb.home.arpa/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
